// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9sGL9drPjVhMNGGshwPSACP65S20a49g',
    appId: '1:635021723313:web:cb061b91b34c3ebbb50490',
    messagingSenderId: '635021723313',
    projectId: 'sumi-86a45',
    authDomain: 'sumi-86a45.firebaseapp.com',
    storageBucket: 'sumi-86a45.firebasestorage.app',
    measurementId: 'G-W2BSEEZP77',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXk5Yew77KskZydAMFGcPcoR4Delbbtqo',
    appId: '1:635021723313:android:47e3aad5951bc3b2b50490',
    messagingSenderId: '635021723313',
    projectId: 'sumi-86a45',
    storageBucket: 'sumi-86a45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQUE2zxEkoa9E3jJ844pbK4iH454Hr7o',
    appId: '1:635021723313:ios:7ab4912a07ad07feb50490',
    messagingSenderId: '635021723313',
    projectId: 'sumi-86a45',
    storageBucket: 'sumi-86a45.firebasestorage.app',
    iosBundleId: 'com.example.sumi',
  );
}
